[2024-03-17T13:09:30.501+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: application_record_processing.read_csv manual__2024-03-17T13:09:28.955318+00:00 [queued]>
[2024-03-17T13:09:30.510+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: application_record_processing.read_csv manual__2024-03-17T13:09:28.955318+00:00 [queued]>
[2024-03-17T13:09:30.511+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-17T13:09:30.524+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): read_csv> on 2024-03-17 13:09:28.955318+00:00
[2024-03-17T13:09:30.529+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-03-17T13:09:30.533+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'application_record_processing', 'read_csv', 'manual__2024-03-17T13:09:28.955318+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpcicvduzt']
[2024-03-17T13:09:30.535+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask read_csv
[2024-03-17T13:09:30.584+0000] {task_command.py:423} INFO - Running <TaskInstance: application_record_processing.read_csv manual__2024-03-17T13:09:28.955318+00:00 [running]> on host 6cb0e4687a92
[2024-03-17T13:09:30.679+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='application_record_processing' AIRFLOW_CTX_TASK_ID='read_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T13:09:28.955318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-17T13:09:28.955318+00:00'
[2024-03-17T13:09:30.683+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 11, in read_csv
    df = pd.read_csv(csv_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'c:/DE Project/airflow/dags/application_record.csv'
[2024-03-17T13:09:30.694+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=application_record_processing, task_id=read_csv, execution_date=20240317T130928, start_date=20240317T130930, end_date=20240317T130930
[2024-03-17T13:09:30.705+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task read_csv ([Errno 2] No such file or directory: 'c:/DE Project/airflow/dags/application_record.csv'; 115)
[2024-03-17T13:09:30.747+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T13:09:30.770+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
