[2024-03-17T13:20:57.690+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:20:57.702+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:20:57.703+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-17T13:20:57.717+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): format_standarization> on 2024-03-17 13:10:00+00:00
[2024-03-17T13:20:57.726+0000] {standard_task_runner.py:60} INFO - Started process 327 to run task
[2024-03-17T13:20:57.730+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'application_record_processing', 'format_standarization', 'scheduled__2024-03-17T13:10:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpc877xcpb']
[2024-03-17T13:20:57.731+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask format_standarization
[2024-03-17T13:20:57.779+0000] {task_command.py:423} INFO - Running <TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [running]> on host 6cb0e4687a92
[2024-03-17T13:20:57.855+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='application_record_processing' AIRFLOW_CTX_TASK_ID='format_standarization' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T13:10:00+00:00'
[2024-03-17T13:20:57.857+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: format_standarization() missing 1 required positional argument: 'df'
[2024-03-17T13:20:57.865+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=application_record_processing, task_id=format_standarization, execution_date=20240317T131000, start_date=20240317T132057, end_date=20240317T132057
[2024-03-17T13:20:57.875+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task format_standarization (format_standarization() missing 1 required positional argument: 'df'; 327)
[2024-03-17T13:20:57.902+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T13:20:57.930+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
