[2024-03-17T13:26:02.870+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:26:02.879+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [queued]>
[2024-03-17T13:26:02.880+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-17T13:26:02.893+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): format_standarization> on 2024-03-17 13:10:00+00:00
[2024-03-17T13:26:02.899+0000] {standard_task_runner.py:60} INFO - Started process 136 to run task
[2024-03-17T13:26:02.902+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'application_record_processing', 'format_standarization', 'scheduled__2024-03-17T13:10:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpuvna21wa']
[2024-03-17T13:26:02.904+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask format_standarization
[2024-03-17T13:26:02.955+0000] {task_command.py:423} INFO - Running <TaskInstance: application_record_processing.format_standarization scheduled__2024-03-17T13:10:00+00:00 [running]> on host cc537db63590
[2024-03-17T13:26:03.034+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='application_record_processing' AIRFLOW_CTX_TASK_ID='format_standarization' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T13:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T13:10:00+00:00'
[2024-03-17T13:26:03.035+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: format_standarization() missing 1 required positional argument: 'df'
[2024-03-17T13:26:03.044+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=application_record_processing, task_id=format_standarization, execution_date=20240317T131000, start_date=20240317T132602, end_date=20240317T132603
[2024-03-17T13:26:03.056+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task format_standarization (format_standarization() missing 1 required positional argument: 'df'; 136)
[2024-03-17T13:26:03.074+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T13:26:03.098+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
