[2024-03-17T13:35:56.301+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: application_record_processing.format_standardization scheduled__2024-03-17T13:25:00+00:00 [queued]>
[2024-03-17T13:35:56.309+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: application_record_processing.format_standardization scheduled__2024-03-17T13:25:00+00:00 [queued]>
[2024-03-17T13:35:56.310+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-17T13:35:56.325+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): format_standardization> on 2024-03-17 13:25:00+00:00
[2024-03-17T13:35:56.330+0000] {standard_task_runner.py:60} INFO - Started process 338 to run task
[2024-03-17T13:35:56.332+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'application_record_processing', 'format_standardization', 'scheduled__2024-03-17T13:25:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmptlsldxus']
[2024-03-17T13:35:56.334+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask format_standardization
[2024-03-17T13:35:56.379+0000] {task_command.py:423} INFO - Running <TaskInstance: application_record_processing.format_standardization scheduled__2024-03-17T13:25:00+00:00 [running]> on host cc537db63590
[2024-03-17T13:35:56.446+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='application_record_processing' AIRFLOW_CTX_TASK_ID='format_standardization' AIRFLOW_CTX_EXECUTION_DATE='2024-03-17T13:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-17T13:25:00+00:00'
[2024-03-17T13:35:56.448+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: format_standardization() missing 1 required positional argument: 'df'
[2024-03-17T13:35:56.455+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=application_record_processing, task_id=format_standardization, execution_date=20240317T132500, start_date=20240317T133556, end_date=20240317T133556
[2024-03-17T13:35:56.465+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task format_standardization (format_standardization() missing 1 required positional argument: 'df'; 338)
[2024-03-17T13:35:56.506+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-17T13:35:56.529+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
