[2024-03-17T13:45:07.620+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: application_record_processing.format_standardization scheduled__2024-03-17T13:35:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
