[2024-03-17T13:27:56.946+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: application_record_processing.read_csv manual__2024-03-17T13:27:50.351934+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
